name: PhpInsights
on:
    push:
    release:
        types: [published]

jobs:
    badges:
        name: Generating badges
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                php-version: 7.3
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                coverage: xdebug

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-suggest

            - name: Execute phpinsights
              run: composer phpinsights-analyse

            - name: Generate PhpInsights badges
              uses: Lukasss93/phpinsights-badger@v1
              with:
                  url: 'https://phpinsights.lucapatera.it/'
                  password: ${{ secrets.phpinsights_password }}
                  path : './phpinsights.json'