name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 7.4, 7.3]
                laravel: [8.*, 7.*, 6.*]
                os: [ubuntu-latest]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache/files
                  key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: xdebug

            - name: Install dependencies
              run: |
                composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: composer test-coverage

            - name: Send coverage
              run: composer send-coverage
              env:
                COVERALLS_RUN_LOCALLY: 1
                COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
